'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference_J_E
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/WCF_J_E"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BoolValueField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoolValue() As Boolean
            Get
                Return Me.BoolValueField
            End Get
            Set
                If (Me.BoolValueField.Equals(value) <> true) Then
                    Me.BoolValueField = value
                    Me.RaisePropertyChanged("BoolValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Clases.NACIONALIDADES", [Namespace]:="http://schemas.datacontract.org/2004/07/ClasesBase"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ClasesNACIONALIDADES
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DESCRIPCIONField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ID_NACIONALIDADField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DESCRIPCION() As String
            Get
                Return Me.DESCRIPCIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DESCRIPCIONField, value) <> true) Then
                    Me.DESCRIPCIONField = value
                    Me.RaisePropertyChanged("DESCRIPCION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID_NACIONALIDAD() As Integer
            Get
                Return Me.ID_NACIONALIDADField
            End Get
            Set
                If (Me.ID_NACIONALIDADField.Equals(value) <> true) Then
                    Me.ID_NACIONALIDADField = value
                    Me.RaisePropertyChanged("ID_NACIONALIDAD")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Clases.DET_PERSONAS", [Namespace]:="http://schemas.datacontract.org/2004/07/ClasesBase"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ClasesDET_PERSONAS
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DET_ID_PERSONAField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ID_BANCOField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ID_DET_PERSONAField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ID_MONEDAField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NOMBRE_BField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NOMBRE_MField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NOTASField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NUM_CUENTAField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DET_ID_PERSONA() As Integer
            Get
                Return Me.DET_ID_PERSONAField
            End Get
            Set
                If (Me.DET_ID_PERSONAField.Equals(value) <> true) Then
                    Me.DET_ID_PERSONAField = value
                    Me.RaisePropertyChanged("DET_ID_PERSONA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID_BANCO() As Integer
            Get
                Return Me.ID_BANCOField
            End Get
            Set
                If (Me.ID_BANCOField.Equals(value) <> true) Then
                    Me.ID_BANCOField = value
                    Me.RaisePropertyChanged("ID_BANCO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID_DET_PERSONA() As Integer
            Get
                Return Me.ID_DET_PERSONAField
            End Get
            Set
                If (Me.ID_DET_PERSONAField.Equals(value) <> true) Then
                    Me.ID_DET_PERSONAField = value
                    Me.RaisePropertyChanged("ID_DET_PERSONA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID_MONEDA() As Integer
            Get
                Return Me.ID_MONEDAField
            End Get
            Set
                If (Me.ID_MONEDAField.Equals(value) <> true) Then
                    Me.ID_MONEDAField = value
                    Me.RaisePropertyChanged("ID_MONEDA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NOMBRE_B() As String
            Get
                Return Me.NOMBRE_BField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NOMBRE_BField, value) <> true) Then
                    Me.NOMBRE_BField = value
                    Me.RaisePropertyChanged("NOMBRE_B")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NOMBRE_M() As String
            Get
                Return Me.NOMBRE_MField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NOMBRE_MField, value) <> true) Then
                    Me.NOMBRE_MField = value
                    Me.RaisePropertyChanged("NOMBRE_M")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NOTAS() As String
            Get
                Return Me.NOTASField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NOTASField, value) <> true) Then
                    Me.NOTASField = value
                    Me.RaisePropertyChanged("NOTAS")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NUM_CUENTA() As String
            Get
                Return Me.NUM_CUENTAField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NUM_CUENTAField, value) <> true) Then
                    Me.NUM_CUENTAField = value
                    Me.RaisePropertyChanged("NUM_CUENTA")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Clases.MONEDAS", [Namespace]:="http://schemas.datacontract.org/2004/07/ClasesBase"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ClasesMONEDAS
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DESCRIPCIONField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ID_MONEDAField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DESCRIPCION() As String
            Get
                Return Me.DESCRIPCIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DESCRIPCIONField, value) <> true) Then
                    Me.DESCRIPCIONField = value
                    Me.RaisePropertyChanged("DESCRIPCION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID_MONEDA() As Integer
            Get
                Return Me.ID_MONEDAField
            End Get
            Set
                If (Me.ID_MONEDAField.Equals(value) <> true) Then
                    Me.ID_MONEDAField = value
                    Me.RaisePropertyChanged("ID_MONEDA")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Clases.BANCOS", [Namespace]:="http://schemas.datacontract.org/2004/07/ClasesBase"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ClasesBANCOS
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ID_BANCOField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NOMBREField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID_BANCO() As Integer
            Get
                Return Me.ID_BANCOField
            End Get
            Set
                If (Me.ID_BANCOField.Equals(value) <> true) Then
                    Me.ID_BANCOField = value
                    Me.RaisePropertyChanged("ID_BANCO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NOMBRE() As String
            Get
                Return Me.NOMBREField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NOMBREField, value) <> true) Then
                    Me.NOMBREField = value
                    Me.RaisePropertyChanged("NOMBRE")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference_J_E.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
        Function GetData(ByVal value As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
        Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService1/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContract(ByVal composite As ServiceReference_J_E.CompositeType) As ServiceReference_J_E.CompositeType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService1/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContractAsync(ByVal composite As ServiceReference_J_E.CompositeType) As System.Threading.Tasks.Task(Of ServiceReference_J_E.CompositeType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/LOGIN_EMPLEADOS", ReplyAction:="http://tempuri.org/IService1/LOGIN_EMPLEADOSResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ServiceReference_J_E.ClasesNACIONALIDADES())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ServiceReference_J_E.ClasesNACIONALIDADES)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ServiceReference_J_E.ClasesDET_PERSONAS())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ServiceReference_J_E.ClasesDET_PERSONAS)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ServiceReference_J_E.ClasesMONEDAS())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ServiceReference_J_E.ClasesMONEDAS)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ServiceReference_J_E.ClasesBANCOS())),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ServiceReference_J_E.ClasesBANCOS)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ServiceReference_J_E.CompositeType))>  _
        Function LOGIN_EMPLEADOS(ByVal Usuario As String, ByVal Contrasenia As String) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/LOGIN_EMPLEADOS", ReplyAction:="http://tempuri.org/IService1/LOGIN_EMPLEADOSResponse")>  _
        Function LOGIN_EMPLEADOSAsync(ByVal Usuario As String, ByVal Contrasenia As String) As System.Threading.Tasks.Task(Of Object)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SEL_NACIONALIDADES", ReplyAction:="http://tempuri.org/IService1/SEL_NACIONALIDADESResponse")>  _
        Function SEL_NACIONALIDADES() As ServiceReference_J_E.ClasesNACIONALIDADES()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SEL_NACIONALIDADES", ReplyAction:="http://tempuri.org/IService1/SEL_NACIONALIDADESResponse")>  _
        Function SEL_NACIONALIDADESAsync() As System.Threading.Tasks.Task(Of ServiceReference_J_E.ClasesNACIONALIDADES())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SEL_DET_PERSONAS", ReplyAction:="http://tempuri.org/IService1/SEL_DET_PERSONASResponse")>  _
        Function SEL_DET_PERSONAS() As ServiceReference_J_E.ClasesDET_PERSONAS()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SEL_DET_PERSONAS", ReplyAction:="http://tempuri.org/IService1/SEL_DET_PERSONASResponse")>  _
        Function SEL_DET_PERSONASAsync() As System.Threading.Tasks.Task(Of ServiceReference_J_E.ClasesDET_PERSONAS())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/INS_DET_PERSONAS", ReplyAction:="http://tempuri.org/IService1/INS_DET_PERSONASResponse")>  _
        Function INS_DET_PERSONAS(ByVal DET_PERSONA As ServiceReference_J_E.ClasesDET_PERSONAS) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/INS_DET_PERSONAS", ReplyAction:="http://tempuri.org/IService1/INS_DET_PERSONASResponse")>  _
        Function INS_DET_PERSONASAsync(ByVal DET_PERSONA As ServiceReference_J_E.ClasesDET_PERSONAS) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SEL_MONEDAS", ReplyAction:="http://tempuri.org/IService1/SEL_MONEDASResponse")>  _
        Function SEL_MONEDAS() As ServiceReference_J_E.ClasesMONEDAS()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SEL_MONEDAS", ReplyAction:="http://tempuri.org/IService1/SEL_MONEDASResponse")>  _
        Function SEL_MONEDASAsync() As System.Threading.Tasks.Task(Of ServiceReference_J_E.ClasesMONEDAS())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SEL_BANCOS", ReplyAction:="http://tempuri.org/IService1/SEL_BANCOSResponse")>  _
        Function SEL_BANCOS() As ServiceReference_J_E.ClasesBANCOS()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SEL_BANCOS", ReplyAction:="http://tempuri.org/IService1/SEL_BANCOSResponse")>  _
        Function SEL_BANCOSAsync() As System.Threading.Tasks.Task(Of ServiceReference_J_E.ClasesBANCOS())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits ServiceReference_J_E.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of ServiceReference_J_E.IService1)
        Implements ServiceReference_J_E.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetData(ByVal value As Integer) As String Implements ServiceReference_J_E.IService1.GetData
            Return MyBase.Channel.GetData(value)
        End Function
        
        Public Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String) Implements ServiceReference_J_E.IService1.GetDataAsync
            Return MyBase.Channel.GetDataAsync(value)
        End Function
        
        Public Function GetDataUsingDataContract(ByVal composite As ServiceReference_J_E.CompositeType) As ServiceReference_J_E.CompositeType Implements ServiceReference_J_E.IService1.GetDataUsingDataContract
            Return MyBase.Channel.GetDataUsingDataContract(composite)
        End Function
        
        Public Function GetDataUsingDataContractAsync(ByVal composite As ServiceReference_J_E.CompositeType) As System.Threading.Tasks.Task(Of ServiceReference_J_E.CompositeType) Implements ServiceReference_J_E.IService1.GetDataUsingDataContractAsync
            Return MyBase.Channel.GetDataUsingDataContractAsync(composite)
        End Function
        
        Public Function LOGIN_EMPLEADOS(ByVal Usuario As String, ByVal Contrasenia As String) As Object Implements ServiceReference_J_E.IService1.LOGIN_EMPLEADOS
            Return MyBase.Channel.LOGIN_EMPLEADOS(Usuario, Contrasenia)
        End Function
        
        Public Function LOGIN_EMPLEADOSAsync(ByVal Usuario As String, ByVal Contrasenia As String) As System.Threading.Tasks.Task(Of Object) Implements ServiceReference_J_E.IService1.LOGIN_EMPLEADOSAsync
            Return MyBase.Channel.LOGIN_EMPLEADOSAsync(Usuario, Contrasenia)
        End Function
        
        Public Function SEL_NACIONALIDADES() As ServiceReference_J_E.ClasesNACIONALIDADES() Implements ServiceReference_J_E.IService1.SEL_NACIONALIDADES
            Return MyBase.Channel.SEL_NACIONALIDADES
        End Function
        
        Public Function SEL_NACIONALIDADESAsync() As System.Threading.Tasks.Task(Of ServiceReference_J_E.ClasesNACIONALIDADES()) Implements ServiceReference_J_E.IService1.SEL_NACIONALIDADESAsync
            Return MyBase.Channel.SEL_NACIONALIDADESAsync
        End Function
        
        Public Function SEL_DET_PERSONAS() As ServiceReference_J_E.ClasesDET_PERSONAS() Implements ServiceReference_J_E.IService1.SEL_DET_PERSONAS
            Return MyBase.Channel.SEL_DET_PERSONAS
        End Function
        
        Public Function SEL_DET_PERSONASAsync() As System.Threading.Tasks.Task(Of ServiceReference_J_E.ClasesDET_PERSONAS()) Implements ServiceReference_J_E.IService1.SEL_DET_PERSONASAsync
            Return MyBase.Channel.SEL_DET_PERSONASAsync
        End Function
        
        Public Function INS_DET_PERSONAS(ByVal DET_PERSONA As ServiceReference_J_E.ClasesDET_PERSONAS) As Boolean Implements ServiceReference_J_E.IService1.INS_DET_PERSONAS
            Return MyBase.Channel.INS_DET_PERSONAS(DET_PERSONA)
        End Function
        
        Public Function INS_DET_PERSONASAsync(ByVal DET_PERSONA As ServiceReference_J_E.ClasesDET_PERSONAS) As System.Threading.Tasks.Task(Of Boolean) Implements ServiceReference_J_E.IService1.INS_DET_PERSONASAsync
            Return MyBase.Channel.INS_DET_PERSONASAsync(DET_PERSONA)
        End Function
        
        Public Function SEL_MONEDAS() As ServiceReference_J_E.ClasesMONEDAS() Implements ServiceReference_J_E.IService1.SEL_MONEDAS
            Return MyBase.Channel.SEL_MONEDAS
        End Function
        
        Public Function SEL_MONEDASAsync() As System.Threading.Tasks.Task(Of ServiceReference_J_E.ClasesMONEDAS()) Implements ServiceReference_J_E.IService1.SEL_MONEDASAsync
            Return MyBase.Channel.SEL_MONEDASAsync
        End Function
        
        Public Function SEL_BANCOS() As ServiceReference_J_E.ClasesBANCOS() Implements ServiceReference_J_E.IService1.SEL_BANCOS
            Return MyBase.Channel.SEL_BANCOS
        End Function
        
        Public Function SEL_BANCOSAsync() As System.Threading.Tasks.Task(Of ServiceReference_J_E.ClasesBANCOS()) Implements ServiceReference_J_E.IService1.SEL_BANCOSAsync
            Return MyBase.Channel.SEL_BANCOSAsync
        End Function
    End Class
End Namespace
